import {
    FaPalette,
    FaMagnifyingGlass,
    FaVial,
    FaHandPointer,
    FaCubes,
    FaSitemap,
    FaObjectGroup,
    FaMobileScreen,
    FaChartPie,
    FaChartBar,
    FaHeart,
    FaBrain,
    FaPuzzlePiece,
    FaComments,
    FaArrowsRotate,
    FaEye
} from "react-icons/fa6";

export const skillsData = [
    { id: 1, text: "UI Design", icon: FaPalette },
    { id: 2, text: "UX Research", icon: FaMagnifyingGlass },
    { id: 3, text: "Usability Testing", icon: FaVial },
    { id: 4, text: "Interaction Design", icon: FaHandPointer },
    { id: 5, text: "Prototyping", icon: FaCubes },
    { id: 6, text: "Information Architecture", icon: FaSitemap },
    { id: 7, text: "Wireframing", icon: FaObjectGroup },
    { id: 8, text: "Responsive Design", icon: FaMobileScreen },
    { id: 9, text: "Data Visualization", icon: FaChartPie },
    { id: 10, text: "Analytics", icon: FaChartBar },
    { id: 11, text: "User Empathy", icon: FaHeart },
    { id: 12, text: "Analytical Thinking", icon: FaBrain },
    { id: 13, text: "Problem Solving", icon: FaPuzzlePiece },
    { id: 14, text: "Clear Communication", icon: FaComments },
    { id: 15, text: "Adaptability", icon: FaArrowsRotate },
    { id: 16, text: "Attention to Detail", icon: FaEye },
];