import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import ThemeButton from "@/components/StickyButtons/ThemeButton";
import AboutPageButton from "@/components/StickyButtons/AboutPageButton";

const futura = localFont({
  src: "./fonts/Futura.otf",
  variable: "--font-futura",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${futura.variable} ${geistSans.variable} ${geistMono.variable} antialiased hide-scrollbar`}
      >
        {children}
        <Footer />
        <ThemeButton />
        <AboutPageButton />
      </body>
    </html>
  );
}
