import { Geist, Geist_Mono, Caveat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

import Footer from "@/components/Footer";
import ThemeButton from "@/components/StickyButtons/ThemeButton";
import AboutPageButton from "@/components/StickyButtons/AboutPageButton";
import ClientRouteGate from "@/components/ClientRouteGate";

const futura = localFont({
  src: "./fonts/Futura.otf",
  variable: "--font-futura",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={[
          futura.variable,
          geistSans.variable,
          geistMono.variable,
          caveat.variable,
          "select-none antialiased hide-scrollbar bg-[var(--background)]",
        ].join(" ")}
      >
        {children}

        {/* Client-only route aware UI */}
        <ClientRouteGate>
          <Footer />
          <ThemeButton />
          <AboutPageButton />
        </ClientRouteGate>
      </body>
    </html>
  );
}
